name: build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - run: npm ci
        working-directory: ./website
        
      - run: npm run build
        working-directory: ./website
        
      - run: touch ./website/out/.nojekyll
      
      - name: Deploy to gh-pages
        run: |
          cd ./website/out
          git init
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
